[book]
authors = ["Nathaniel Brough"]
language = "en"
multilingual = false
src = "src"
title = "dialectic"
google_analytics_id = "G-57HPN3C093"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]